# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

resources:
- repo: self

variables:
  repositoryDocker: 'netcordovaleon/skillnestjavadevops'
  version: '1.0'
  usuarioSonar: 'lcordova'
  passwordSonar: '123'

stages:
  - stage: PublicarImagen
    displayName: Contruir Imagen proyecto Java-Docker
    jobs:
    - job: Build
      displayName: Build Docker Image
      pool:
        vmImage: ubuntu-latest
      steps:


      - task: Docker@2
        displayName: Docker Build
        inputs:
          containerRegistry: 'DockerLuisCordova'
          repository: '$(repositoryDocker)'
          command: 'build'
          Dockerfile: '**/Dockerfile'
      - task: Docker@2
        displayName: Docker Push
        inputs:
          containerRegistry: 'DockerLuisCordova'
          repository: '$(repositoryDocker)'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
      - task: CmdLine@2
        inputs:
          script: |
            echo Write your commands here
            
            echo Hello world $(repositoryDocker)
#Stage de ejemplo solo para visualizar 2 etapas en nuestro pipeline
  - stage: FinalDevOps
    displayName: Stage final del ejemplo
    jobs:
    - job: FinalizarDevops
      displayName: Finalizar DevOps
      steps:
      - task: CmdLine@2
        inputs:
          script: |
            echo Write your commands here
            
            echo Fin del proceso de pipelines