# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    #- task: Docker@2
    #  displayName: Build an image
    #  inputs:
    #    command: build
    #    dockerfile: '$(Build.SourcesDirectory)/skillnest.docker/example-using-dockerfile/com.skillnest.docker/Dockerfile'
    #    tags: |
    #      $(tag)
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerLuisCordova'
        dockerfile: '$(Build.SourcesDirectory)/skillnest.docker/example-using-dockerfile/com.skillnest.docker/Dockerfile'
        repository: 'netcordovaleon/skillnestjava'
        command: 'buildAndPush'
