version: "3.1"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver2019
    ports:
    - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: SQL123456@_
    networks:
      - fullstack
    volumes:
      - ./database:/var/opt/mssql/data     
  backend:
    container_name: backend
    build: ./example-using-dockerfile/com.skillnest.docker
    ports:
      - "8080:8080"
    networks:
      - fullstack
    depends_on:
      - sqlserver
    environment:
      - DATABASE_HOST=sqlserver
      - DATABASE_USER=sa
      - DATABASE_PASSWORD=SQL123456@_
      - DATABASE_NAME=springexample  
      - DATABASE_PORT=1433
networks:
  fullstack: